package paplikasitokosigab1;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.*;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.util.JRLoader.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.export.*;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRException;
import java.util.*;
import java.io.*;
import java.lang.*;
import java.sql.*;
import javax.swing.*;
import java.util.HashMap;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.lang.NullPointerException;
import java.io.FileNotFoundException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.lang.Object;


public class Aplikasi_Menu_Utama extends javax.swing.JFrame {

Connection c;
ResultSet r;
Statement s;
   
    public Aplikasi_Menu_Utama() {
        initComponents();
        BukaKoneksi();
        SetMenu(true);
        tusername.requestFocus();
    }
    
    private void BukaKoneksi() {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://localhost/db_tokosigab1","root","");
            System.out.println("Koneksi Sukses");
        }
         catch(Exception e){
        System.out.println(e);
        }
}
    
    private void SetMenu(boolean b){
        mfile.setEnabled(!b);
        maplikasi.setEnabled(!b);
        mlaporan.setEnabled(!b);
        mabout.setEnabled(!b);
        
    }
    
    private void BersihField(){
        tusername.setText("");
        tpassword.setText("");
        tusername.requestFocus();
    }
    
    private void ExitWindow(){
    int confirmed = JOptionPane.showConfirmDialog(null, "Keluar Dari Program","Exit",JOptionPane.YES_NO_OPTION );
    if (confirmed == JOptionPane.YES_OPTION )
    {
        dispose();
    }else
    {
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    tusername.requestFocus();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        tpassword = new javax.swing.JTextField();
        tbuka = new javax.swing.JButton();
        tkeluar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mfile = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        maplikasi = new javax.swing.JMenu();
        amb = new javax.swing.JCheckBoxMenuItem();
        ams = new javax.swing.JCheckBoxMenuItem();
        amp = new javax.swing.JCheckBoxMenuItem();
        atp = new javax.swing.JCheckBoxMenuItem();
        atpj = new javax.swing.JCheckBoxMenuItem();
        mlaporan = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        lbarang = new javax.swing.JMenuItem();
        lsupplier = new javax.swing.JCheckBoxMenuItem();
        lpegawai = new javax.swing.JCheckBoxMenuItem();
        lpembelian = new javax.swing.JCheckBoxMenuItem();
        lpenjualan = new javax.swing.JCheckBoxMenuItem();
        jMenu18 = new javax.swing.JMenu();
        lgab1 = new javax.swing.JMenuItem();
        lgab2 = new javax.swing.JMenuItem();
        lgab3 = new javax.swing.JMenuItem();
        lgab4 = new javax.swing.JMenuItem();
        lgab5 = new javax.swing.JMenuItem();
        mabout = new javax.swing.JMenu();

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI MENU UTAMA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Silakan Masukkan Username dan Password");

        jLabel3.setText("User Name");

        jLabel4.setText("Password");

        tusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tusernameKeyPressed(evt);
            }
        });

        tpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tpasswordKeyPressed(evt);
            }
        });

        tbuka.setText("BUKA");
        tbuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbukaActionPerformed(evt);
            }
        });

        tkeluar.setText("KELUAR");
        tkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkeluarActionPerformed(evt);
            }
        });

        mfile.setText("File");
        mfile.setName("mfile"); // NOI18N

        jMenu3.setText("Open");
        mfile.add(jMenu3);

        jMenu4.setText("Save");
        mfile.add(jMenu4);

        jMenu5.setText("Update Login");
        mfile.add(jMenu5);
        mfile.add(jSeparator1);

        jMenu6.setText("Exit");
        mfile.add(jMenu6);

        jMenuBar1.add(mfile);

        maplikasi.setText("Aplikasi");
        maplikasi.setName("maplikasi"); // NOI18N

        amb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        amb.setSelected(true);
        amb.setText("Aplikasi Master Barang");
        amb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambActionPerformed(evt);
            }
        });
        maplikasi.add(amb);

        ams.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        ams.setSelected(true);
        ams.setText("Aplikasi Master Supplier");
        ams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amsActionPerformed(evt);
            }
        });
        maplikasi.add(ams);

        amp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        amp.setSelected(true);
        amp.setText("Aplikasi Master Pegawai");
        amp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ampActionPerformed(evt);
            }
        });
        maplikasi.add(amp);

        atp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        atp.setSelected(true);
        atp.setText("Aplikasi Transaksi Pembelian");
        atp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpActionPerformed(evt);
            }
        });
        maplikasi.add(atp);

        atpj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        atpj.setSelected(true);
        atpj.setText("Aplikasi Transaksi Penjualan");
        atpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atpjActionPerformed(evt);
            }
        });
        maplikasi.add(atpj);

        jMenuBar1.add(maplikasi);

        mlaporan.setText("Laporan");
        mlaporan.setName("mlaporan"); // NOI18N

        jMenu13.setText("Laporan Tabel Tunggal");

        lbarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        lbarang.setText("Laporan Tabel Barang");
        lbarang.setName("lbarang"); // NOI18N
        lbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbarangActionPerformed(evt);
            }
        });
        jMenu13.add(lbarang);

        lsupplier.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        lsupplier.setSelected(true);
        lsupplier.setText("Laporan Tabel Supplier");
        lsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsupplierActionPerformed(evt);
            }
        });
        jMenu13.add(lsupplier);

        lpegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        lpegawai.setSelected(true);
        lpegawai.setText("Laporan Tabel Pegawai");
        lpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpegawaiActionPerformed(evt);
            }
        });
        jMenu13.add(lpegawai);

        lpembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        lpembelian.setSelected(true);
        lpembelian.setLabel("Laporan Tabel Pembelian");
        lpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpembelianActionPerformed(evt);
            }
        });
        jMenu13.add(lpembelian);

        lpenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        lpenjualan.setSelected(true);
        lpenjualan.setText("Laporan Tabel Penjualan");
        lpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lpenjualanActionPerformed(evt);
            }
        });
        jMenu13.add(lpenjualan);

        mlaporan.add(jMenu13);

        jMenu18.setText("Laporan Tabel Gabungan");

        lgab1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        lgab1.setText("Laporan Gabungan Dua Tabel");
        lgab1.setName("lgab1"); // NOI18N
        lgab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgab1ActionPerformed(evt);
            }
        });
        jMenu18.add(lgab1);

        lgab2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        lgab2.setText("Laporan Gabungan Tiga Tabel");
        lgab2.setName("lgab2"); // NOI18N
        lgab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgab2ActionPerformed(evt);
            }
        });
        jMenu18.add(lgab2);

        lgab3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        lgab3.setText("Laporan Gabungan Empat Tabel");
        lgab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgab3ActionPerformed(evt);
            }
        });
        jMenu18.add(lgab3);

        lgab4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK));
        lgab4.setText("Laporan Gabungan Lima Tabel");
        lgab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgab4ActionPerformed(evt);
            }
        });
        jMenu18.add(lgab4);

        lgab5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.ALT_MASK));
        lgab5.setText("Laporan Gabungan Enam Tabel");
        lgab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgab5ActionPerformed(evt);
            }
        });
        jMenu18.add(lgab5);

        mlaporan.add(jMenu18);

        jMenuBar1.add(mlaporan);

        mabout.setText("About");
        mabout.setName("mabout"); // NOI18N
        jMenuBar1.add(mabout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tusername)
                            .addComponent(tpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(tbuka, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(tkeluar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbuka)
                    .addComponent(tkeluar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbarangActionPerformed
    //BUAT MENAMPILKAN LAPORAN ATAU REPORT BARANG
        String sql = "Select * from barang";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptbarang.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }
    }//GEN-LAST:event_lbarangActionPerformed

    private void tbukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbukaActionPerformed
        try{
            String user=tusername.getText();
            String pass=new String(tpassword.getText());
            s=c.createStatement();
        String sql="Select * from login Where username='"+user+"' And password='"+pass+"'";
            r=s.executeQuery(sql);
            int baris=0;
            while(r.next()){
                baris=r.getRow();
            }
            if(baris==1){
                SetMenu(false);
                BersihField();
                JOptionPane.showMessageDialog(null,"Login Berhasil");
                tusername.setEnabled(false);
                tpassword.setEnabled(false);
                tbuka.setEnabled(false);
            }
            else{
                 SetMenu(true);
                BersihField();
                JOptionPane.showMessageDialog(null,"Login Gagal");
            }
        }
         catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_tbukaActionPerformed

    private void lgab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgab1ActionPerformed
        String sql = "Select * FROM gabbrgbeli";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptgab_barang_beli.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }
    }//GEN-LAST:event_lgab1ActionPerformed

    private void tkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkeluarActionPerformed
        ExitWindow();
    }//GEN-LAST:event_tkeluarActionPerformed

    private void lpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpegawaiActionPerformed
        String sql = "Select * FROM pegawai";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptpegawai.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }
    }//GEN-LAST:event_lpegawaiActionPerformed

    private void lsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsupplierActionPerformed
        String sql = "Select * FROM supplier";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptsupplier.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }
    }//GEN-LAST:event_lsupplierActionPerformed

    private void lgab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgab2ActionPerformed
     String sql = "Select * FROM gab3tabel";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptgab_barang_beli_jual.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }   
    }//GEN-LAST:event_lgab2ActionPerformed

    private void lpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpembelianActionPerformed
       String sql = "Select * FROM pembelian";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptpembelian.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }   
    }//GEN-LAST:event_lpembelianActionPerformed

    private void lgab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgab4ActionPerformed
        String sql = "Select * FROM gab5tabel";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptgab5tabel.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }  
    }//GEN-LAST:event_lgab4ActionPerformed

    private void lpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lpenjualanActionPerformed
        String sql = "Select * FROM penjualan";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptpenjualan.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }  
    }//GEN-LAST:event_lpenjualanActionPerformed

    private void lgab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgab3ActionPerformed
        String sql = "Select * FROM gab4tabel";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptgab4tabel.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }  
    }//GEN-LAST:event_lgab3ActionPerformed

    private void lgab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgab5ActionPerformed
         String sql = "Select * FROM gab6tabel";
    try{
        ResultSet r = s.executeQuery(sql);
        JasperPrint JasperPrint;
        JRResultSetDataSource jrRs = new JRResultSetDataSource (r);
        JasperReport JasperReport = JasperCompileManager.compileReport("./src/paplikasitokosigab1/rptgab6tabel.jrxml");
        JasperPrint = JasperFillManager.fillReport(JasperReport, null, jrRs);
        JRViewer aViewer = new JRViewer(JasperPrint);
        JDialog viewer = new JDialog();
        viewer.setTitle(".: Jasper Report :.");
        viewer.setAlwaysOnTop(true);
        viewer.getContentPane().add(aViewer);
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        viewer.setBounds(0,0,screensize.width, screensize.height);
        viewer.setVisible(true);
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Laporan Sip"+e);
    }  
    }//GEN-LAST:event_lgab5ActionPerformed

    private void tusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tusernameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tpassword.requestFocus();
        }
    }//GEN-LAST:event_tusernameKeyPressed

    private void tpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpasswordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           // tusername.requestFocus();
            tbukaActionPerformed(new ActionEvent(c, WIDTH, null));
        }
    }//GEN-LAST:event_tpasswordKeyPressed

    private void ambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambActionPerformed
        new Aplikasi_Master_Barang().setVisible(true);
    }//GEN-LAST:event_ambActionPerformed

    private void amsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amsActionPerformed
        new Aplikasi_Master_Supplier().setVisible(true);
    }//GEN-LAST:event_amsActionPerformed

    private void ampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ampActionPerformed
        new Aplikasi_Master_Pegawai().setVisible(true);
    }//GEN-LAST:event_ampActionPerformed

    private void atpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpActionPerformed
        new Aplikasi_Transaksi_Pembelian().setVisible(true);
    }//GEN-LAST:event_atpActionPerformed

    private void atpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atpjActionPerformed
        new Aplikasi_Transaksi_Penjualan().setVisible(true);
    }//GEN-LAST:event_atpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi_Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem amb;
    private javax.swing.JCheckBoxMenuItem amp;
    private javax.swing.JCheckBoxMenuItem ams;
    private javax.swing.JCheckBoxMenuItem atp;
    private javax.swing.JCheckBoxMenuItem atpj;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem lbarang;
    private javax.swing.JMenuItem lgab1;
    private javax.swing.JMenuItem lgab2;
    private javax.swing.JMenuItem lgab3;
    private javax.swing.JMenuItem lgab4;
    private javax.swing.JMenuItem lgab5;
    private javax.swing.JCheckBoxMenuItem lpegawai;
    private javax.swing.JCheckBoxMenuItem lpembelian;
    private javax.swing.JCheckBoxMenuItem lpenjualan;
    private javax.swing.JCheckBoxMenuItem lsupplier;
    private javax.swing.JMenu mabout;
    private javax.swing.JMenu maplikasi;
    private javax.swing.JMenu mfile;
    private javax.swing.JMenu mlaporan;
    private javax.swing.JButton tbuka;
    private javax.swing.JButton tkeluar;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
