
package paplikasitokosigab1;

//ini import
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

public class Aplikasi_Master_Supplier extends javax.swing.JFrame {
    
    //KONEKSI
    Connection c;
    ResultSet r;
    Statement s;
    private Object[][]datasupplier=null;
    private String[] label={"Kode Supplier","Nama Perusahaan","Nama Penanggung Jawab","Nomor Telepon","Email","Alamat"};
    
    public Aplikasi_Master_Supplier(){
    initComponents();
    BukaKoneksi();
    BacaTabelSupplier();
    tbl_sup.setVisible(true);
    
    tkd_sup.requestFocus();
    }
    private void BukaKoneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        c=DriverManager.getConnection("jdbc:mysql://localhost/db_tokosigab1","root","");
        System.out.println("Koneksi Sukses");
    }
    catch(Exception e){
    System.out.println(e);
    }
    }
    
    private void BacaTabelSupplier(){
    try{
        
    s=c.createStatement();
    String sql="Select*From supplier Order By kd_sup";
    r=s.executeQuery(sql);
    ResultSetMetaData m=r.getMetaData();
    int kolom=m.getColumnCount();
    int baris=0;
    while(r.next()){
    baris=r.getRow();
    }
    datasupplier=new Object[baris][kolom];
    int x=0;
    r.beforeFirst();
        while (r.next()) {            
            datasupplier[x][0]=r.getString("kd_sup");
            datasupplier[x][1]=r.getString("nm_per");
            datasupplier[x][2]=r.getString("nm_pen");
            datasupplier[x][3]=r.getString("no_telp");
            datasupplier[x][4]=r.getString("email");
            datasupplier[x][5]=r.getString("alamat");
            x++;
        }
        tbl_sup.setModel(new DefaultTableModel(datasupplier,label));
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
    }
    }
    
    private void SetTabel(){
        int row=tbl_sup.getSelectedRow();
        tkd_sup.setText((String)tbl_sup.getValueAt(row,0));
        tnm_per.setText((String)tbl_sup.getValueAt(row,1));
        tnm_pen.setText((String)tbl_sup.getValueAt(row,2));
        tno_telp.setText((String)tbl_sup.getValueAt(row,3));
        temail.setText((String)tbl_sup.getValueAt(row,4));
        talamat.setText((String)tbl_sup.getValueAt(row,5));
    }
    
     private void BersihField(){
        tkd_sup.setText("");
        tnm_per.setText("");
        tnm_pen.setText("");
        tno_telp.setText("");
        temail.setText("");
        talamat.setText("");
    }
     
    private void SimpanData(){
        try{
            String sql="Insert Into supplier Values('"+tkd_sup.getText()+"','"+tnm_per.getText()+"','"+tnm_pen.getText()+"','"+tno_telp.getText()+"','"+temail.getText()+"','"+talamat.getText()+"')";
                   
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(null,"Data berhasil ditambah");
            BersihField();
            BacaTabelSupplier();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
        private void UpdateData(){
        try{
           String sql="Update supplier Set kd_sup='"+tkd_sup.getText()+"',nm_per='"+tnm_per.getText()+"',nm_pen='"+tnm_per.getText()+"',no_telp='"+tno_telp.getText()+"',email='"+temail.getText()+"',alamat='"+talamat.getText()+"'Where kd_sup='"+tkd_sup.getText()+"'";
           
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(null,"Data Berhasil diedit");
            BersihField();
            BacaTabelSupplier();
            }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
        
        private void HapusData(){
        try{
            String sql="Delete from supplier where kd_sup='"+tkd_sup.getText()+"'";
            s.executeUpdate(sql);
            s.close();
            JOptionPane.showMessageDialog(null,"Data Berhasil dihapus");
            BersihField();
            BacaTabelSupplier();
        }
            catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
            }
        }

    //EXIT
    private void ExitWindow(){
    int confirmed = JOptionPane.showConfirmDialog(null, "Keluar Dari Program","Exit",JOptionPane.YES_NO_OPTION );
    if (confirmed == JOptionPane.YES_OPTION )
    {
        dispose();
    }else
    {
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    tkd_sup.requestFocus();
    }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sup = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tkd_sup = new javax.swing.JTextField();
        tnm_per = new javax.swing.JTextField();
        tnm_pen = new javax.swing.JTextField();
        tno_telp = new javax.swing.JTextField();
        temail = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        bt_tambah = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_keluar = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI MASTER SUPPLIER");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setDisplayedMnemonic('h');
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TABEL DATA SUPPLIER");

        tbl_sup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Suplier", "Nama Perusahaan", "Nama Penanggung Jawab", "No Telp", "Email", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_sup.setName("tbl_sup"); // NOI18N
        tbl_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_supMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sup);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("INPUT DATA SUPPLIER");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Kode Supplier");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setText("Nama Perusahaan");

        jLabel5.setText("Nama Penanggungjawab");

        jLabel6.setText("No Telp");

        jLabel7.setText("Email");

        jLabel8.setText("Alamat");

        tkd_sup.setToolTipText("test");
        tkd_sup.setName("tkd_sup"); // NOI18N
        tkd_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkd_supActionPerformed(evt);
            }
        });
        tkd_sup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tkd_supKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tkd_supKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tkd_supKeyTyped(evt);
            }
        });

        tnm_per.setName("tnm_per"); // NOI18N
        tnm_per.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnm_perKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnm_perKeyReleased(evt);
            }
        });

        tnm_pen.setName("tnm_pen"); // NOI18N
        tnm_pen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnm_penKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnm_penKeyReleased(evt);
            }
        });

        tno_telp.setName("tno_telp"); // NOI18N
        tno_telp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tno_telpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tno_telpKeyReleased(evt);
            }
        });

        temail.setName("temail"); // NOI18N
        temail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                temailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                temailKeyReleased(evt);
            }
        });

        talamat.setName("talamat"); // NOI18N
        talamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talamatActionPerformed(evt);
            }
        });
        talamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                talamatKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                talamatKeyReleased(evt);
            }
        });

        bt_tambah.setText("Tambah");
        bt_tambah.setName("bt_tambah"); // NOI18N
        bt_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahActionPerformed(evt);
            }
        });

        bt_edit.setText("Edit");
        bt_edit.setName("bt_edit"); // NOI18N
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.setName("bt_hapus"); // NOI18N
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_keluar.setText("Keluar");
        bt_keluar.setName("bt_keluar"); // NOI18N
        bt_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(bt_tambah)
                                .addGap(61, 61, 61)
                                .addComponent(bt_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(bt_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(bt_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tkd_sup)
                                    .addComponent(tnm_per)
                                    .addComponent(tnm_pen)
                                    .addComponent(tno_telp)
                                    .addComponent(temail)
                                    .addComponent(talamat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tkd_sup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnm_per, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnm_pen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tno_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(talamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_hapus)
                    .addComponent(bt_tambah)
                    .addComponent(bt_edit)
                    .addComponent(bt_keluar))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tkd_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkd_supActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkd_supActionPerformed

    private void talamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talamatActionPerformed

    private void bt_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahActionPerformed
    int confirmed = JOptionPane.showConfirmDialog(null, "Tambah Data","Simpan",JOptionPane.YES_NO_OPTION );
    if (confirmed == JOptionPane.YES_OPTION )
    {
        SimpanData();
        tkd_sup.requestFocus();
    }else
    {
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    tkd_sup.requestFocus();
    }
    }//GEN-LAST:event_bt_tambahActionPerformed

    private void bt_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_keluarActionPerformed
       ExitWindow();
    }//GEN-LAST:event_bt_keluarActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
    int confirmed = JOptionPane.showConfirmDialog(null, "Hapus Data","Hapus",JOptionPane.YES_NO_OPTION );
    if (confirmed == JOptionPane.YES_OPTION )
    {
       HapusData();
    }else
    {
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    tkd_sup.requestFocus();
    }  
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     ExitWindow();
    }//GEN-LAST:event_formWindowClosing

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
    int confirmed = JOptionPane.showConfirmDialog(null, "Edit Data","Edit",JOptionPane.YES_NO_OPTION );
    if (confirmed == JOptionPane.YES_OPTION )
    {
        UpdateData();
    }else
    {
    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    tkd_sup.requestFocus();
    }
    }//GEN-LAST:event_bt_editActionPerformed

    private void tkd_supKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tkd_supKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tnm_per.requestFocus();
        }
    }//GEN-LAST:event_tkd_supKeyPressed

    private void tnm_perKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnm_perKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tnm_pen.requestFocus();
         }
    }//GEN-LAST:event_tnm_perKeyPressed

    private void tnm_penKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnm_penKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            tno_telp.requestFocus();
         }
    }//GEN-LAST:event_tnm_penKeyPressed

    private void tno_telpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tno_telpKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            temail.requestFocus();
         }
    }//GEN-LAST:event_tno_telpKeyPressed

    private void temailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temailKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            talamat.requestFocus();
         }
    }//GEN-LAST:event_temailKeyPressed

    private void talamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_talamatKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            //tkd_sup.requestFocus();
             bt_tambahActionPerformed(new ActionEvent(c, WIDTH, null));
         }
    }//GEN-LAST:event_talamatKeyPressed

    private void tbl_supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_supMouseClicked
        SetTabel();
    }//GEN-LAST:event_tbl_supMouseClicked

    private void tkd_supKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tkd_supKeyTyped
       //COBA
    }//GEN-LAST:event_tkd_supKeyTyped

    private void tkd_supKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tkd_supKeyReleased
        try{
            Statement s=c.createStatement();
            String search=tkd_sup.getText();
            ResultSet r=s.executeQuery("Select * from supplier where kd_sup like '%"+search+"%'");
            DefaultTableModel dtm=(DefaultTableModel)tbl_sup.getModel();
            dtm.setRowCount(0);
            String [] data=new String[6];
            int i=1;
            while (r.next())
            {
                data[0]=r.getString("kd_sup");
                data[1]=r.getString("nm_per");
                data[2]=r.getString("nm_pen");
                data[3]=r.getString("no_telp");
                data[4]=r.getString("email");
                data[5]=r.getString("alamat");
                dtm.addRow(data);
                i++;
            }
                r.close();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data yang Anda cari tidak ditemukan");
            System.err.println("error (search): "+e);
        }
            String input=tkd_sup.getText();
        if(input.length()>10){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            tkd_sup.setText("");
        }
    }//GEN-LAST:event_tkd_supKeyReleased

    private void tnm_perKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnm_perKeyReleased
       String input=tnm_per.getText();
        if(input.length()>20){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            tnm_per.setText("");
        }
    }//GEN-LAST:event_tnm_perKeyReleased

    private void tnm_penKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnm_penKeyReleased
        String input=tnm_pen.getText();
        if(input.length()>20){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            tnm_pen.setText("");
        }
    }//GEN-LAST:event_tnm_penKeyReleased

    private void tno_telpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tno_telpKeyReleased
       String input=tno_telp.getText();
        if(input.length()>15){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            tno_telp.setText("");
        }
    }//GEN-LAST:event_tno_telpKeyReleased

    private void temailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_temailKeyReleased
        String input=temail.getText();
        if(input.length()>20){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            temail.setText("");
        }
    }//GEN-LAST:event_temailKeyReleased

    private void talamatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_talamatKeyReleased
        String input=talamat.getText();
        if(input.length()>30){
            JOptionPane.showMessageDialog(rootPane,"jumlah input melebihi batas");
            talamat.setText("");
        }
    }//GEN-LAST:event_talamatKeyReleased


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Master_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Master_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Master_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasi_Master_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasi_Master_Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_keluar;
    private javax.swing.JButton bt_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField talamat;
    private javax.swing.JTable tbl_sup;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tkd_sup;
    private javax.swing.JTextField tnm_pen;
    private javax.swing.JTextField tnm_per;
    private javax.swing.JTextField tno_telp;
    // End of variables declaration//GEN-END:variables
}
